### ISSUE TITLE
Find suitable template

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/rogon-web#4]
Need to redesign the website.

Logo file:
[rogon_full.svg.zip](https://github.com/phisoft/rogon-web/files/9037346/rogon_full.svg.zip)

**Comment by russel0907** [comment]
@rosclaritha

**List of Template**

Template 1
https://technext.github.io/unearth/index.html

Template 2
https://technext.github.io/adventure/index.html

Template 3
https://technext.github.io/elma/index.html

Template 4
https://website155736.nicepage.io/Home.html?version=4266581f-bd6e-4a50-ae10-cd056165e791

Template 5
https://beautyofnature.nicepage.io/Page-1.html?version=bf88784b-5732-48b7-a412-476e03e4895c
