### ISSUE TITLE
Redesign website 

### ISSUE THREAD

**Issue by rosclaritha** [phisoft/rogon-web#5]
Proceed to use the following template: 
https://technext.github.io/elma/index.html

**Comment by russel0907** [comment]
Website development current progress for web view 

## Website View
![Screenshot 2022-07-07 at 22-53-07 Rogon Network](https://user-images.githubusercontent.com/94702093/177805489-42ab6e03-622a-4da2-af68-f6c6be853fe5.png)

**Comment by russel0907** [comment]
Update Progress 2
Adjust contain's positioning for mobile responsiveness

## Mobile View
![Screenshot 2022-07-08 at 12-09-50 Rogon Network Wi-Fi Service Provider](https://user-images.githubusercontent.com/94702093/177915422-dc6ed572-63a6-4bd6-9365-979347ba85e2.png)

**Comment by russel0907** [comment]
update ilustration on LOS 

progress 3

![Rogon-Network (1)](https://user-images.githubusercontent.com/94702093/178406445-a2b3ee62-0098-4069-95db-2cd25558bf84.png)

**Comment by russel0907** [comment]
update and redesign image for the solution section

web dev progress

![Screenshot 2022-07-12 at 15-37-09 Rogon Network Wi-Fi Service Provider](https://user-images.githubusercontent.com/94702093/178435474-3d882508-5496-46b9-850e-60543b32f14d.png)
